# Generated by Django 2.1.1 on 2018-09-24 16:50

from django.db import migrations, models
import django.db.models.deletion
import image_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.ImageField(upload_to=image_api.models.scramble_uploaded_filename)),
                ('extension', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransferedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.ImageField(upload_to=image_api.models.scramble_uploaded_filename)),
                ('extension', models.CharField(max_length=100)),
                ('source_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_api.Image')),
            ],
        ),
    ]
