# Generated by Django 2.1.1 on 2018-09-25 16:55

from django.db import migrations, models
import django.db.models.deletion
import image_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0003_auto_20180925_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotatedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.ImageField(upload_to=image_api.models.scramble_uploaded_filename)),
                ('degree', models.IntegerField()),
                ('source_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_api.Image')),
            ],
        ),
    ]
